name = "client-pack-okaka"
author = "nocox"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4c629f8ac84cb8fe02ee4f61de179331788b353398de3a2e8aab80722d99dea5"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
