name = "client-pack-okaka"
author = "nocox"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e839ee8806ea34b3f28099290f8a91698c299b9f8b8f58bc60f10860748f42e1"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
