name = "client-pack-yutori"
author = "nocox"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0a521cc59aae91e69124dda94679b7041eb7cf670451514937effb2b530db627"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
