name = "client-pack-26.2"
author = "nocox"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bfcd08d7ede43900ad1e7bcb6bdbfa860008c21ec9a01bd03a80c3bc947dd9e5"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
