name = "client-pack-26.2"
author = "nocox"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e8281fb5ca86800be383e8bb47fcb863614ced67b8eb2f7180c28160c2255bbc"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
