name = "client-pack-26.2"
author = "nocox"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4106efa9c93cb36a723ac3cc6bc6809051654e61e33c68081ea848cc3728e0c6"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
